### ISSUE TITLE
Some great courses on parallel computing

### ISSUE THREAD

**Issue by AlanFreySpace** [tensorush/Awesome-Systems-Programming#1]
1. Manycore Parallel Algorithms [https://lumetta.web.engr.illinois.edu/508/](url)
2. Parallel Computing: Theory and Practice[https://www.cs.cmu.edu/afs/cs/academic/class/15210-f15/www/tapp.htmll](url)
3. Multiprocessor Synchronization[https://cs.brown.edu/courses/cs176/lectures.shtml](url)
4. Applied Parallel Programming[https://lumetta.web.engr.illinois.edu/408-S20/](url)
5. Massively Parallel Algorithms[https://people.inf.ethz.ch/gmohsen/MPA19/](url)
6. Parallel Algorithms[https://www.cs.cmu.edu/afs/cs/academic/class/15499-s09/www/](url)
7. Parallel Computer Architecture and Programming[https://www.cs.cmu.edu/~15418/](url)
8. PARALLEL COMPUTING[https://gfxcourses.stanford.edu/cs149/fall23](url)
9. Parallel Programming[https://www3.cs.stonybrook.edu/~rezaul/](url)
10. Advanced Topics in Parallel Computing[https://www.nm.ifi.lmu.de/teaching/Vorlesungen/2022ss/AdvPar/](url)
11. Parallel and Concurrent Algorithms[https://www.cs.cmu.edu/~guyb/paralg/](url)
12. Applications of Parallel Computers[https://sites.google.com/lbl.gov/cs267-spr2023](url)

**Comment by tensorush** [comment]
Thanks! I've added a [new section for these](https://github.com/tensorush/Awesome-Systems-Programming?tab=readme-ov-file#twisted_rightwards_arrows-parallel-programming).
